DROP TABLE IF EXISTS store;
DROP TABLE IF EXISTS purchases;
DROP TABLE IF EXISTS korzina;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS customers;
